cxx_precompiled_header(
    name = "common_pch",
    src = "common.hpp",
)

cxx_binary(
    name = "client",
    srcs = glob([ "*.cpp" ]),
    visibility = [ "PUBLIC" ],
    # deps = [ "//protos:greeter" ],
    precompiled_header = ":common_pch",
    compiler_flags = [
        "-std=c++1z"
    ],
    linker_flags = [
        "-lsfml-graphics",
        "-lsfml-window",
        "-lsfml-network",
        "-lsfml-system",
    ],
)
